### ISSUE TITLE
can't convert String into Array (TypeError)

### ISSUE THREAD

**Issue by anthonyringoet** [holman/gifme#10]
When I want to use the basic gifme functionality it throws up this error.
Used to work on my setup. Can someone point me in the right direction what's wrong?

``` bash
$ gifme image.gif --reverse
/Library/Ruby/Gems/1.8/gems/gifme-0.0.8/bin/gifme:86:in `+': can't convert String into Array (TypeError)
    from /Library/Ruby/Gems/1.8/gems/gifme-0.0.8/bin/gifme:86
    from /usr/bin/gifme:23:in `load'
    from /usr/bin/gifme:23
```

**Comment by holman** [comment]
You want to give it the images you want to gif- so probably something like:

```
$ gifme images/* --reverse
```

**Comment by anthonyringoet** [comment]
Oh i see where I got confused.
I thought it would work the same as the external gif example

``` bash
$ gifme http://tumblr.com/some-crazy.gif --width=1000
```

Where you just give in the base file (in my example already an animated gif) and the script would make up a name.

**Comment by holman** [comment]
Yeah- that's a good point. I'll keep it in mind (I'm halfway redoing gifme every now and then).
