### ISSUE TITLE
help incorporating into a rails app

### ISSUE THREAD

**Issue by jmolayem** [holman/gifme#15]
Hi homan, great gem. I successfully create a cool gif. Have you had any success or documetation on how one would incorporate this into a rails app?

**Comment by holman** [comment]
Hey! Glad it's working well for you.

gifme was designed specifically as a command-line app, so there's not really an easy way to just drop it in and interact with it with Ruby. You're likely going to want to shell out to use it, something like:

``` ruby
`gifme FILES`
```

...that assumes your shell's set up to know where the PATH of `gifme` is, though. And then you'll need to read the outputted file manually in Rails to stream it back to the user or something like that.

gifme is pretty small in general, though- you might want to bypass the gem entirely and take a look at ImageMagick yourself and shell out to that (or use one of the other ImageMagick-specific libraries to interface with it).

Hopefully that helps some- let me know if you have any questions!
